;;
;;  File:	Makefile.tmpl
;;  Project:	emacs-templates
;;  Desc:
;;
;;	Emacs Lisp source
;;
;;  Notes:
;;
;;  Author(s):   Paul Houghton <paul4hough@gmail.com>
;;  Created:     08/18/2001 08:18

(or template-doc-desc
    (setq template-doc-desc "Build rules and targets"))

(insert
(template-insert-fragment "default-txt.tmpl")
)


;;; Local Variables:
;;; mode:Emacs-Lisp
;;; end:
