;;
;;  File:	Makefile.tmpl
;;  Project:	EmacsTemplates 
;;  Desc:
;;
;;	Emacs Lisp source
;;  
;;  Notes:
;;    
;;  Author(s):   Paul Houghton <pahoughton@users.sourceforge.net>
;;  Created:     08/18/2001 08:18
;;  
;;  Revision Info: (See ChangeLog or cvs log for revision history)
;;  
;;	$Author$
;;	$Date$
;;	$Revision$
;;	$State$
;;
;;  $Id$
;;

(or template-doc-desc
    (setq template-doc-desc "Build rules and targets"))

(insert
(template-insert-fragment "default-txt.tmpl")
)


;;; Local Variables:
;;; mode:Emacs-Lisp
;;; end:
